---
- name: Download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php

- name: Install composer
  become: true
  command: 'php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer'
  args:
    creates: '/usr/local/bin/composer'

- name: Update composer
  become: true
  command: composer self-update
  register: composer_update
  changed_when: "'Updating to version' in composer_update.stdout"

- name: Install global composer packages
  command: "composer global require {{ item.package }}:{{ item.version|default('@stable') }}"
  args:
    creates: '{{ ansible_env.HOME }}/.config/composer/vendor/{{ item.package }}/composer.json'
  with_items: '{{ composer.packages }}'
  when: composer.packages is defined
