- name: Check if certificate exists
  stat:
    path: '/etc/letsencrypt/live/{{ certificate.domains|first }}/fullchain.pem'
  register: certificate_file

- name: Stop service
  become: true
  service:
    name: '{{ certbot.stop_service }}'
    state: stopped
  when: not certificate_file.stat.exists

- name: Generate certificate
  become: true
  command: "certbot certonly --standalone --noninteractive --agree-tos --no-eff-email --email {{ certificate.email }} --domains {{ certificate.domains|join(',') }}"
  args:
    creates: '/etc/letsencrypt/live/{{ certificate.domains|first }}/fullchain.pem'
  when: not certificate_file.stat.exists

- name: Start service
  become: true
  service:
    name: '{{ certbot.stop_service }}'
    state: started
  when:  not certificate_file.stat.exists
