---
- name: Add ppa repository
  become: true
  apt_repository:
    repo: ppa:certbot/certbot

- name: Install certbot
  become: true
  apt:
    name: certbot

- include_tasks: generate-certificate.yml
  with_items: '{{ certbot.certificates }}'
  loop_control:
    loop_var: certificate

- name: Create cronjob to renew certificates
  become: true
  cron:
    job: certbot renew --quiet
    name: Renew certificates
    minute: '{{ certbot.renew_minute }}'
    hour: '{{ certbot.renew_hour }}'
  when: certbot.certificates is defined
