---
- name: Add ppa repository
  become: true
  apt_repository:
    repo: ppa:ondrej/php

- name: Install php-fpm
  become: true
  apt:
    name: 'php{{ php.version }}-fpm'

- name: Install php extensions
  become: true
  apt:
    name: 'php{{ php.version }}-{{ item }}'
  with_items: '{{ php.extensions }}'
  when: php.extensions is defined
  notify: Restart php-fpm

- name: Install php extras
  become: true
  apt:
    name: 'php-{{ item }}'
  with_items: '{{ php.extras }}'
  when: php.extras is defined
  notify: Restart php-fpm
