---
- name: Add ppa repository
  become: true
  apt_repository:
    repo: ppa:ondrej/php

- name: Install php-fpm
  become: true
  apt:
    name: 'php{{ php.version }}-fpm'

- name: Install php extensions
  become: true
  apt:
    name: 'php{{ php.version }}-{{ item }}'
  with_items: '{{ php.extensions }}'
  when: php.extensions is defined
  notify: Restart php-fpm

- name: Disable xdebug on php-fpm
  become: true
  command: phpdismod xdebug
  args:
    removes: '/etc/php/{{ php.version }}/fpm/conf.d/20-xdebug.ini'
  notify: Restart php-fpm

- name: Modify php settings
  become: true
  lineinfile:
    dest: '/etc/php/{{ php.version }}/{{ item[0] }}/php.ini'
    regexp: ';?{{ item[1].setting }} ?=.*'
    line: '{{ item[1].setting }} = {{ item[1].value }}'
  with_nested:
    - [fpm, cli]
    - '{{ php.settings }}'
  notify: Restart php-fpm

- name: Remove default php-fpm pool
  become: true
  file:
    path: '/etc/php/{{ php.version }}/fpm/pool.d/www.conf'
    state: absent
  when: php.fpm_pools is defined
  notify: Restart php-fpm

- name: Create php-fpm pools
  become: true
  template:
    src: fpm-pool.conf
    dest: '/etc/php/{{ php.version }}/fpm/pool.d/{{ item.name }}.conf'
  with_items: '{{ php.fpm_pools }}'
  when: php.fpm_pools is defined
  notify: Restart php-fpm
